### ISSUE TITLE
关于voj.web.war部署的问题

### ISSUE THREAD

**Issue by Ruanxingzhi** [zjhzxhz/voj#8]
我的系统：Ubuntu 15.10 64位，Tomcat8。

今晚用tomcat-manager尝试部署web.war，出现如下错误提示：
```
Message: 	
FAIL - Application at context path /web could not be started
```

请问应该如何解决？

**Comment by zjhzxhz** [comment]
请问有其他的日志吗？
比如有没有异常什么的？

**Comment by Ruanxingzhi** [comment]
Tomcat Manager部署提示是这样：
```
Message: 	
FAIL - Application at context path /web could not be started
```

浏览器访问是404错误。

catalina.out这样写道：
```
五月 23, 2016 6:49:23 下午 org.apache.catalina.core.StandardContext startInternal
严重: One or more listeners failed to start. Full details will be found in the appropriate container log file
五月 23, 2016 6:49:23 下午 org.apache.catalina.core.StandardContext startInternal
严重: Context [/web] startup failed due to previous errors
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
警告: The web application [web] registered the JDBC driver [com.alibaba.druid.proxy.DruidDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
警告: The web application [web] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
 com.mysql.jdbc.AbandonedConnectionCleanupThread.run(AbandonedConnectionCleanupThread.java:43)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-2090014775] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-2090014775] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-423056824] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-423056824] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1729427563] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1729427563] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-2047810609] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-2047810609] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-16862492] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-16862492] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1504679880] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1504679880] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-790267895] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-790267895] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-503971929] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-503971929] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1695003280] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1695003280] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1086708587] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1086708587] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-26294427] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-26294427] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-2115848595] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-2115848595] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-732041462] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-732041462] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1620562398] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1620562398] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-1885373970] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-1885373970] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Create-748799576] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:1861)
五月 23, 2016 6:49:23 下午 org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads
警告: The web application [web] appears to have started a thread named [Druid-ConnectionPool-Destroy-748799576] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 com.alibaba.druid.pool.DruidDataSource$DestroyConnectionThread.run(DruidDataSource.java:1935)
```

打扰了，抱歉！

**Comment by zjhzxhz** [comment]
不打扰呢~

你看日志的第二行, `五月 23, 2016 6:49:23 下午 org.apache.catalina.core.StandardContext startInternal
严重: Context [/web] startup failed due to previous errors`.

请问Previous Errors是什么? 应该上面还有异常栈的信息吧.

凭现有的信息感觉是数据库有问题, 你导入voj.sql了吗?

**Comment by Ruanxingzhi** [comment]
mysql已经导入了，图：http://i4.buimg.com/4e3f00c6e891c89d.png
另外，voj.properties中的mysql用户名和密码也设置好了。

具体的错误日志在这：https://coding.net/u/ruanxingzhi/p/File/git/tree/master

感谢！

**Comment by zjhzxhz** [comment]
```
Caused by: javax.jms.JMSException: Could not connect to broker URL: tcp://localhost:61616. Reason: java.net.ConnectException: 拒绝连接
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:360)
	at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:305)
	at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:245)
	at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:365)
	at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:305)
	at org.springframework.jms.connection.SingleConnectionFactory.getConnection(SingleConnectionFactory.java:283)
	at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:224)
	at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:413)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.establishSharedConnection(AbstractJmsListeningContainer.java:381)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.doStart(AbstractJmsListeningContainer.java:285)
	at org.springframework.jms.listener.SimpleMessageListenerContainer.doStart(SimpleMessageListenerContainer.java:210)
	at org.springframework.jms.listener.AbstractJmsListeningContainer.start(AbstractJmsListeningContainer.java:270)
	... 23 more
```

消息队列没有启动呢~
你需要安装ActiveMQ, 并启动之~
